spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:taste-archive
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # 개발환경에서는 편의상 create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

# 운영환경과 다른 개발용 jwt 키 값
jwt:
  key: OewPcNeX7cy++FrTqVsB14Fg8kC9xaphxD9LEdWu170=

cloud:
  aws:
    s3:
      bucket: test-value
    credentials:
      access-key: test-value
      secret-key: test-value
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spotify:
  client-id: eb9c2bc88c014e5e9a78cdb743d7a6df
  client-secret: 0ca8f3e352bd4f8082044c6c5eb64023
  get-token-url: https://accounts.spotify.com/api/token