name: Deploy Application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: ssh -o ServerAliveInterval=600 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "/home/ec2-user/deploy.sh"